version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://siddheshpednekar_db_user:Restaurant%40123@demoappcluster.dpg1arx.mongodb.net/SmartRestaurantDB?retryWrites=true&w=majority
      - JWT_SECRET=supersecretkey

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
